# Generated by Django 2.0.4 on 2018-04-05 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todoitem',
            old_name='to_do_item',
            new_name='todo_item',
        ),
    ]
